{% set name = "python-build" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: 1a07724e891cbd898923145eb7752ee7653674c511378eb9c7691aab1612bc3c

build:
  number: 0
  noarch: python
  entry_points:
    - python-build = build.__main__:entrypoint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - colorama
    - importlib-metadata >=0.22
    - packaging >=19.0
    - pep517 >=0.9.1
    - tomli >=1.0.0

test:
  imports:
    - build
  commands:
    - pip check
    - python-build --help
  requires:
    - pip

about:
  home: https://github.com/pypa/build
  license: MIT
  license_file: LICENSE
  summary: A simple, correct PEP 517 build frontend

extra:
  recipe-maintainers:
    - ocefpaf
