{% set name = "python-build" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: d5b71264afdb5951d6704482aac78de887c80691c52b88a9ad195983ca2c9269

build:
  number: 0
  noarch: python
  entry_points:
    - python-build = build.__main__:entrypoint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=3.4
  run:
    - python >=3.7
    - colorama
    - importlib-metadata >=0.22
    - packaging >=19.0
    - pyproject_hooks
    - tomli >=1.1.0
  run_constrained:
    - build <0

test:
  imports:
    - build
  commands:
    - pip check
    - python-build --help
  requires:
    - pip

about:
  home: https://github.com/pypa/build
  license: MIT
  license_file: LICENSE
  summary: A simple, correct PEP 517 build frontend

extra:
  recipe-maintainers:
    - ocefpaf
    - henryiii
